package workflowpress

// generate_templates.go holds the template bodies the Generator renders. They are
// kept out of generate.go so the generator logic stays small and the templates
// stay reviewable as a unit. Every template renders the deterministic specView
// (generate.go) and must avoid any non-deterministic input (time, randomness, map
// iteration). Maps are only ever read through the view's sorted accessors.
//
// The emitted Go files declare the workflow as DATA and a thin Run entrypoint
// that delegates to the kernel Runner — the generator never re-implements the
// state machine, it embeds the contract and points the kernel at it. That keeps
// the generated tool's behavior identical to the kernel's and to the durable
// adapter's.

// tmplWorkflow emits the generated package's entrypoint: the embedded canonical
// spec and a Run that decodes it and drives the kernel Runner. The generated
// package is self-contained except for the workflowpress kernel import.
const tmplWorkflow = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// Workflow: {{.Spec.ID}} (version {{.Spec.Version}})
// Goal: {{.Spec.Goal}}
// Operator: {{.Spec.Operator}}
//
// This is the operator's generated internal tool. It embeds the frozen contract
// and runs it through the workflowpress kernel Runner — the same runtime the
// shipcheck replays and the durable adapter re-hosts, so all three paths behave
// identically. Actions run through the fail-closed Executor seam; external writes
// are gated and recorded, never performed live.
package {{.Package}}

import (
	"context"
	"encoding/json"
	"fmt"

	wp "github.com/nex-crm/wuphf/internal/workflowpress"
)

// specJSON is the frozen contract this tool was generated from, embedded verbatim
// so the runtime decodes the exact spec. It is emitted as a double-quoted,
// strconv.Quote-escaped Go string literal rather than a raw-string (backtick)
// literal: a raw-string literal terminates early on any backtick in the spec's
// free text (json.MarshalIndent does not escape backticks), which would break the
// generated Go. The quoted form survives any byte and decodes identically.
const specJSON = {{.SpecJSONLiteral}}

// loadSpec decodes the embedded contract. It is deterministic and cannot fail for
// the generated bytes; the error path exists only for defence in depth.
func loadSpec() (*wp.WorkflowSpec, error) {
	var spec wp.WorkflowSpec
	if err := json.Unmarshal([]byte(specJSON), &spec); err != nil {
		return nil, fmt.Errorf("{{.Spec.ID}}: decoding embedded spec: %w", err)
	}
	return &spec, nil
}

// Run executes the workflow over one input and returns the kernel RunResult: the
// ordered transition log plus the recorded (and gated) action calls. The host
// executor is fail-closed, so any external write is recorded as gated, never run.
func Run(ctx context.Context, in wp.RunInput) (*wp.RunResult, error) {
	spec, err := loadSpec()
	if err != nil {
		return nil, err
	}
	runner, err := wp.NewRunner(spec, wp.NewHostExecutor(), wp.DefaultGuardEvaluator{})
	if err != nil {
		return nil, fmt.Errorf("{{.Spec.ID}}: building runner: %w", err)
	}
	return runner.Run(ctx, in)
}
`

// tmplTypes emits one struct per entity, fields as strings (the contract is the
// schema; we do not infer field types). Entity order follows the spec.
const tmplTypes = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// Entity types for workflow {{.Spec.ID}}. One struct per domain object the
// workflow moves. Fields are modelled as strings — the contract names the fields;
// concrete typing is the operator's to refine after review.
package {{.Package}}
{{range .Spec.Entities}}
// {{export .Name}} — {{.Description}}
// Trust tier: {{.Provenance.TrustTier}} (confidence {{.Provenance.Confidence}}).
type {{export .Name}} struct { {{range .Fields}}
	{{export .}} string ` + "`" + `json:"{{.}},omitempty"` + "`" + `{{end}}
}
{{end}}`

// tmplExceptions emits the known exceptions as documented constants so the
// handling is discoverable in code, plus a lookup table.
const tmplExceptions = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// Known exceptions for workflow {{.Spec.ID}} and how each is handled, lifted from
// the contract. These are the edge cases the operator told us about; the runtime
// does not auto-handle them, but the generated tool documents them so a reviewer
// and any later handler can see the intended behavior.
package {{.Package}}

// Exception is a known edge/failure case carried from the contract.
type Exception struct {
	Name     string
	When     string
	Handling string
}

// Exceptions are the workflow's known exceptions in contract order.
var Exceptions = []Exception{ {{range .Spec.Exceptions}}
	{Name: {{quote .Name}}, When: {{quote .When}}, Handling: {{quote .Handling}}},{{end}}
}
`

// tmplState emits the state-machine tables as data: the ordered states (with the
// initial/terminal flags), the transitions, and the guards. This is the human-
// readable mirror of what the embedded spec drives.
const tmplState = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// State-machine tables for workflow {{.Spec.ID}}, mirrored from the contract for
// readability. The runtime drives the embedded spec (workflow.go); these tables
// are the same data in Go form so the state graph is reviewable without decoding
// JSON.
package {{.Package}}

// StateNames are the workflow states in contract order; the first is the initial
// state.
var StateNames = []string{ {{range .StateNames}}
	{{quote .}},{{end}}
}

// TerminalStates are the states that end a run.
var TerminalStates = []string{ {{range .Spec.States}}{{if .Terminal}}
	{{quote .Name}},{{end}}{{end}}
}

// Transition is one edge of the state machine.
type Transition struct {
	Event   string
	From    string
	To      string
	Guard   string
	Trigger string
}

// Transitions are the workflow's transitions in contract order.
var Transitions = []Transition{ {{range .Spec.Events}}
	{Event: {{quote .Name}}, From: {{quote .From}}, To: {{quote .To}}, Guard: {{quote .Guard}}, Trigger: {{quote .Trigger}}},{{end}}
}

// Guard is a named gating condition.
type Guard struct {
	Name string
	Expr string
}

// Guards are the workflow's guards in contract order.
var Guards = []Guard{ {{range .Spec.Guards}}
	{Name: {{quote .Name}}, Expr: {{quote .Expr}}},{{end}}
}
`

// tmplInngest emits the durable adapter: the InngestStep plan as data plus a Run
// that delegates to the same kernel Runner via the local adapter. Behavior-
// equivalent to the local path by construction; inngest is the durable target.
const tmplInngest = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// Durable adapter for workflow {{.Spec.ID}}.
//
// inngest is the intended durable execution target: each step below maps to one
// inngest function (scheduled steps to crons, external/internal steps to event
// functions). The inngest Go SDK is not yet a dependency, so this adapter ships a
// behavior-equivalent local runtime (RunDurable) that drives the SAME kernel
// Runner as the local path. The next phase's adapter-parity shipcheck asserts the
// two paths produce identical RunResults.
package {{.Package}}

import (
	"context"

	wp "github.com/nex-crm/wuphf/internal/workflowpress"
)

// DurableStep is one durable execution step: a single contract transition,
// addressable by its function id. Mirrors wp.InngestStep.
type DurableStep struct {
	FunctionID string
	Event      string
	From       string
	To         string
	Trigger    string
	Schedule   string
}

// DurableSteps is the step plan for the durable adapter, one per contract event.
var DurableSteps = []DurableStep{ {{range .Steps}}
	{FunctionID: {{quote .FunctionID}}, Event: {{quote .Event}}, From: {{quote .From}}, To: {{quote .To}}, Trigger: {{quote .Trigger}}, Schedule: {{quote .Schedule}}},{{end}}
}

// RunDurable executes the workflow over one input through the durable adapter. It
// is behavior-equivalent to Run (workflow.go): both delegate to the kernel
// Runner, so the durable and local paths cannot drift.
func RunDurable(ctx context.Context, in wp.RunInput) (*wp.RunResult, error) {
	spec, err := loadSpec()
	if err != nil {
		return nil, err
	}
	adapter, err := wp.NewLocalAdapter(spec)
	if err != nil {
		return nil, err
	}
	return adapter.Run(ctx, in)
}
`

// tmplDoc emits operator-facing documentation of the generated tool.
const tmplDoc = `# {{.Spec.ID}} — generated workflow

> Generated by the Workflow Press from the frozen contract (version {{.Spec.Version}}).
> Do not edit the generated Go by hand — update the contract and regenerate.

**Goal.** {{.Spec.Goal}}

**Operator.** {{.Spec.Operator}}

## States

{{range .Spec.States}}- ` + "`" + `{{.Name}}` + "`" + `{{if .Initial}} (initial){{end}}{{if .Terminal}} (terminal){{end}} — {{.Description}}
{{end}}
## Transitions

{{range .Spec.Events}}- ` + "`" + `{{.From}}` + "`" + ` → ` + "`" + `{{.To}}` + "`" + ` on **{{.Name}}** ({{.Trigger}}{{if .Schedule}}, ` + "`" + `{{.Schedule}}` + "`" + `{{end}}){{if .Guard}} guarded by ` + "`" + `{{.Guard}}` + "`" + `{{end}}
{{end}}
## Actions

{{range .Spec.Actions}}- **{{.Name}}** ({{.Kind}}) on ` + "`" + `{{.On}}` + "`" + `{{if .Target}} → {{.Target}}{{end}}{{if .RequiresApproval}} — requires approval{{end}}{{if .Idempotent}} — idempotent{{end}}
{{end}}
## Exceptions

{{range .Spec.Exceptions}}- **{{.Name}}**: when {{.When}} — {{.Handling}}
{{end}}
## SLAs

{{range .Spec.SLAs}}- **{{.Name}}**: {{.Metric}} ≤ {{.Threshold}}
{{end}}
## Verification scenarios

{{range .Scenarios}}- **{{.Name}}** — fire ` + "`" + `{{.When}}` + "`" + `{{if .ExpectApproval}} (expects approval){{end}}; expects {{len .Expect}} transition(s)
{{end}}
## Execution safety

Actions run through the Workflow Press Executor seam. In this phase the only
backend is the fail-closed host stub: every external write is recorded as **gated**
and is never performed live. The durable adapter (` + "`" + `inngest.go` + "`" + `) is
behavior-equivalent to the local runtime.
`

// tmplTest emits a generated test that replays every verification scenario through
// the generated Run and asserts the transitions (and the approval expectation).
// It uses only the standard library and the generated package.
const tmplTest = `// Code generated by workflowpress.Generate; DO NOT EDIT.
//
// Replays every verification scenario from the contract through the generated
// Run and asserts the expected transitions and approval expectation. This is the
// contract carrying its own tests: the generated tool proves itself against the
// fixtures the operator reviewed.
package {{.Package}}

import (
	"context"
	"testing"

	wp "github.com/nex-crm/wuphf/internal/workflowpress"
)

func TestVerificationScenarios(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name           string
		when           string
		given          map[string]string
		expect         []wp.Transition
		expectApproval bool
	}{ {{range .Scenarios}}
		{
			name: {{quote .Name}},
			when: {{quote .When}},
			given: map[string]string{ {{$g := .Given}}{{range .GivenKeys}}
				{{quote .}}: {{quote (index $g .)}},{{end}}
			},
			expect: []wp.Transition{ {{range .Expect}}
				{From: {{quote .From}}, To: {{quote .To}}},{{end}}
			},
			expectApproval: {{.ExpectApproval}},
		},{{end}}
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			res, err := Run(context.Background(), wp.RunInput{Event: tc.when, Fields: tc.given})
			if err != nil {
				t.Fatalf("Run(%s): %v", tc.when, err)
			}
			if len(res.Transitions) != len(tc.expect) {
				t.Fatalf("got %d transitions, want %d: %+v", len(res.Transitions), len(tc.expect), res.Transitions)
			}
			for i, want := range tc.expect {
				got := res.Transitions[i]
				if got.From != want.From || got.To != want.To {
					t.Errorf("transition %d = %s->%s, want %s->%s", i, got.From, got.To, want.From, want.To)
				}
			}
			if res.ApprovalRequested != tc.expectApproval {
				t.Errorf("approval requested = %v, want %v", res.ApprovalRequested, tc.expectApproval)
			}
		})
	}
}
`
