package workflow

import (
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// generate.go is stage 3 of the press: from the proven contract, emit a typed
// local runner (Go) and an inngest adapter (TS). Both are DERIVED from the same
// spec and embed the spec's transition table verbatim, so shipcheck's
// adapter_parity check can re-parse each artifact and prove neither drifted from
// the contract. The generated runner is the deterministic tool; the inngest
// adapter is the durable-execution binding.

// Generated holds the emitted artifacts plus the transition table they encode.
type Generated struct {
	GoSource      string       `json:"-"`
	InngestSource string       `json:"-"`
	Transitions   []Transition `json:"transitions"`
}

// Generate produces the Go runner + inngest adapter for a spec. It fails if the
// emitted Go is not valid (format.Source rejects it), so a bad generator can
// never ship broken code.
func Generate(s *Spec) (Generated, error) {
	tj, err := json.Marshal(s.Transitions)
	if err != nil {
		return Generated{}, fmt.Errorf("marshal transitions: %w", err)
	}
	goSrc, err := generateGo(s, string(tj))
	if err != nil {
		return Generated{}, err
	}
	return Generated{
		GoSource:      goSrc,
		InngestSource: generateInngest(s, string(tj)),
		Transitions:   s.Transitions,
	}, nil
}

func generateGo(s *Spec, transitionsJSON string) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by workflow.Generate from workflow-spec %q. DO NOT EDIT.\n", s.ID)
	b.WriteString("package genwf\n\n")
	b.WriteString("import \"encoding/json\"\n\n")

	b.WriteString("// State / Event / Action constants (the typed surface).\n")
	b.WriteString("const (\n")
	for _, st := range s.States {
		fmt.Fprintf(&b, "\t%s = %q\n", goIdent("State", st.ID), st.ID)
	}
	for _, ev := range s.Events {
		fmt.Fprintf(&b, "\t%s = %q\n", goIdent("Event", ev.ID), ev.ID)
	}
	for _, ac := range s.Actions {
		fmt.Fprintf(&b, "\t%s = %q\n", goIdent("Action", ac.ID), ac.ID)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Initial is the entry state of the workflow.\n")
	fmt.Fprintf(&b, "const Initial = %q\n\n", s.Initial)

	b.WriteString("// transitionsJSON embeds the contract this runner encodes; adapter_parity\n")
	b.WriteString("// re-parses it to prove no drift from the workflow-spec.\n")
	fmt.Fprintf(&b, "const transitionsJSON = `%s`\n\n", transitionsJSON)

	b.WriteString("type transition struct {\n")
	b.WriteString("\tFrom    string   `json:\"from\"`\n")
	b.WriteString("\tTo      string   `json:\"to\"`\n")
	b.WriteString("\tOn      string   `json:\"on\"`\n")
	b.WriteString("\tGuard   string   `json:\"guard,omitempty\"`\n")
	b.WriteString("\tActions []string `json:\"actions,omitempty\"`\n")
	b.WriteString("}\n\n")

	b.WriteString("func table() []transition {\n")
	b.WriteString("\tvar t []transition\n")
	b.WriteString("\t_ = json.Unmarshal([]byte(transitionsJSON), &t)\n")
	b.WriteString("\treturn t\n")
	b.WriteString("}\n\n")

	b.WriteString("// Advance returns the next state and the actions to run for (state, event).\n")
	b.WriteString("// ok is false when no transition matches. Guard evaluation is performed by\n")
	b.WriteString("// the caller against event data (guards are carried in the table).\n")
	b.WriteString("func Advance(state, event string) (next string, actions []string, ok bool) {\n")
	b.WriteString("\tfor _, t := range table() {\n")
	b.WriteString("\t\tif t.From == state && t.On == event {\n")
	b.WriteString("\t\t\treturn t.To, t.Actions, true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn state, nil, false\n")
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("generated Go is invalid: %w", err)
	}
	return string(formatted), nil
}

func generateInngest(s *Spec, transitionsJSON string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by workflow.Generate from workflow-spec %q. DO NOT EDIT.\n", s.ID)
	b.WriteString("import { inngest } from \"./client\";\n\n")
	fmt.Fprintf(&b, "export const transitionsJSON = `%s`;\n\n", transitionsJSON)
	b.WriteString("type GenTransition = { from: string; to: string; on: string; guard?: string; actions?: string[] };\n")
	b.WriteString("const transitions = JSON.parse(transitionsJSON) as GenTransition[];\n\n")
	fmt.Fprintf(&b, "export const %s = inngest.createFunction(\n", jsIdent(s.ID))
	fmt.Fprintf(&b, "  { id: %q },\n", s.ID)
	fmt.Fprintf(&b, "  { event: %q },\n", s.ID+"/event")
	b.WriteString("  async ({ event, step }) => {\n")
	b.WriteString("    const t = transitions.find((t) => t.from === event.data.state && t.on === event.data.event);\n")
	b.WriteString("    if (!t) return { state: event.data.state, ok: false };\n")
	b.WriteString("    for (const a of t.actions ?? []) {\n")
	b.WriteString("      await step.run(a, async () => ({}));\n")
	b.WriteString("    }\n")
	b.WriteString("    return { state: t.to, actions: t.actions ?? [], ok: true };\n")
	b.WriteString("  },\n")
	b.WriteString(");\n")
	return b.String()
}

// extractTransitionsJSON pulls the backtick-delimited transitionsJSON literal
// out of a generated source (Go or TS) and parses it. This is what proves the
// EMITTED SOURCE encodes the contract, not just the in-memory manifest.
func extractTransitionsJSON(src string) ([]Transition, error) {
	const marker = "transitionsJSON"
	i := strings.Index(src, marker)
	if i < 0 {
		return nil, fmt.Errorf("no transitionsJSON in source")
	}
	open := strings.IndexByte(src[i:], '`')
	if open < 0 {
		return nil, fmt.Errorf("no opening backtick after transitionsJSON")
	}
	open += i + 1
	close := strings.IndexByte(src[open:], '`')
	if close < 0 {
		return nil, fmt.Errorf("no closing backtick for transitionsJSON")
	}
	var out []Transition
	if err := json.Unmarshal([]byte(src[open:open+close]), &out); err != nil {
		return nil, fmt.Errorf("parse embedded transitions: %w", err)
	}
	return out, nil
}

// transitionsEqual compares two transition slices by canonical JSON, so nil vs
// empty Actions never causes a false mismatch.
func transitionsEqual(a, b []Transition) bool {
	ja, err1 := json.Marshal(a)
	jb, err2 := json.Marshal(b)
	return err1 == nil && err2 == nil && string(ja) == string(jb)
}

func goIdent(prefix, id string) string {
	var b strings.Builder
	b.WriteString(prefix)
	for _, part := range splitIdent(id) {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func jsIdent(id string) string {
	parts := splitIdent(id)
	if len(parts) == 0 {
		return "workflowFn"
	}
	var b strings.Builder
	b.WriteString(strings.ToLower(parts[0]))
	for _, part := range parts[1:] {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	b.WriteString("Fn")
	return b.String()
}

func splitIdent(id string) []string {
	return strings.FieldsFunc(id, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
}
