name: Approve on Comment

on:
  issue_comment:
    types: [created]

jobs:
  approve:
    uses: nex-crm/.github/.github/workflows/approve-on-comment.yml@v1
    secrets:
      APPROVER_APP_PRIVATE_KEY: ${{ secrets.APPROVER_APP_PRIVATE_KEY }}
