package team

// wiki_compile_index.go — regenerates the content catalog at team/index.md, the
// Karpathy "index" artifact: a flat, generated listing of every compiled page
// grouped by kind. This is a CONTENT page (markdown in the wiki, browsable like
// any article), distinct from the app's derived catalog UI (index/all.md) — the
// two coexist by design.
//
// The page is fully deterministic: pages are grouped into Concepts and
// Entities and sorted by slug within each group, so a recompile of unchanged
// inputs yields byte-identical output (and folds to a no-op at the commit
// layer).

import (
	"context"
	"sort"
	"strings"
)

// compiledIndexPath is the on-disk location of the generated content index.
const compiledIndexPath = "team/index.md"

// compiledIndexMarker is the generated-by header that warns humans the file is
// machine-owned. It also lets tooling recognize the page as compiler output.
const compiledIndexMarker = "<!-- compiled-index: generated by the wiki compiler. Do not edit by hand. -->"

// compiledPageRef is the lightweight handle the finalize passes (interlink,
// index, log) carry for one live compiled page — enough to link, list, and
// locate it without re-reading frontmatter.
type compiledPageRef struct {
	Slug    string
	Kind    string
	Title   string
	Summary string
	RelPath string
}

// buildIndexMarkdown renders the deterministic team/index.md body for the given
// live pages. Pages are grouped Concepts then Entities, each sorted by slug.
func buildIndexMarkdown(pages []compiledPageRef) string {
	var concepts, entities []compiledPageRef
	for _, p := range pages {
		if conceptKind(p.Kind) == "entity" {
			entities = append(entities, p)
		} else {
			concepts = append(concepts, p)
		}
	}
	sortPageRefs(concepts)
	sortPageRefs(entities)

	var b strings.Builder
	b.WriteString(compiledIndexMarker)
	b.WriteString("\n\n# Wiki Index\n")
	writeIndexSection(&b, "Concepts", concepts)
	writeIndexSection(&b, "Entities", entities)
	return b.String()
}

// writeIndexSection renders one "## {heading}" block. An empty group renders a
// "_None yet._" placeholder so the section structure is stable across runs.
func writeIndexSection(b *strings.Builder, heading string, pages []compiledPageRef) {
	b.WriteString("\n## ")
	b.WriteString(heading)
	b.WriteString("\n\n")
	if len(pages) == 0 {
		b.WriteString("_None yet._\n")
		return
	}
	for _, p := range pages {
		b.WriteString("- [[")
		b.WriteString(p.Slug)
		b.WriteString("|")
		b.WriteString(strings.TrimSpace(p.Title))
		b.WriteString("]]")
		if s := strings.TrimSpace(p.Summary); s != "" {
			b.WriteString(" — ")
			b.WriteString(s)
		}
		b.WriteString("\n")
	}
}

// sortPageRefs orders a page slice by slug for deterministic output.
func sortPageRefs(pages []compiledPageRef) {
	sort.Slice(pages, func(i, j int) bool { return pages[i].Slug < pages[j].Slug })
}

// writeCompiledIndex regenerates team/index.md through the single-writer worker
// in "replace" mode. A byte-identical regen folds to a no-op at the commit
// layer, so calling this every compile is cheap.
func writeCompiledIndex(ctx context.Context, worker *WikiWorker, pages []compiledPageRef) error {
	body := buildIndexMarkdown(pages)
	if _, _, err := worker.Enqueue(ctx, ArchivistAuthor, compiledIndexPath, body, "replace", "compile: regenerate index"); err != nil {
		return err
	}
	return nil
}
